# Generated by Django 2.0.1 on 2018-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=10000)),
                ('Timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
